"""remove created by column

Revision ID: 05785b896490
Revises: a643750b3d94
Create Date: 2024-09-12 14:10:53.582565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05785b896490'
down_revision = 'a643750b3d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_members_created_by_users', 'members', type_='foreignkey')
    op.drop_column('members', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_members_created_by_users', 'members', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
