"""remove device column

Revision ID: 09c152793eb5
Revises: d5a0ee98c472
Create Date: 2024-10-18 09:03:50.097141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c152793eb5'
down_revision = 'd5a0ee98c472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reports_device_id_devices', 'reports', type_='foreignkey')
    op.drop_column('reports', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_reports_device_id_devices', 'reports', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
