"""add device column

Revision ID: 120a191ef164
Revises: 09c152793eb5
Create Date: 2024-10-18 09:26:35.240663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120a191ef164'
down_revision = '09c152793eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_reports_device_id_devices'), 'reports', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reports_device_id_devices'), 'reports', type_='foreignkey')
    op.drop_column('reports', 'device_id')
    # ### end Alembic commands ###
