"""remove campaign relationship from timeseries

Revision ID: 31c4cccc507d
Revises: 73b52b222bd5
Create Date: 2024-10-03 20:35:21.484521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c4cccc507d'
down_revision = '73b52b222bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_timeseries_campaign_id', 'timeseries', type_='unique')
    op.create_unique_constraint(op.f('uq_timeseries_name'), 'timeseries', ['name'])
    op.drop_constraint('fk_timeseries_campaign_id_campaigns', 'timeseries', type_='foreignkey')
    op.drop_constraint('fk_timeseries_campaign_scope_id_c_scopes', 'timeseries', type_='foreignkey')
    op.drop_column('timeseries', 'campaign_id')
    op.drop_column('timeseries', 'campaign_scope_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('campaign_scope_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('timeseries', sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_timeseries_campaign_scope_id_c_scopes', 'timeseries', 'c_scopes', ['campaign_scope_id'], ['id'])
    op.create_foreign_key('fk_timeseries_campaign_id_campaigns', 'timeseries', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(op.f('uq_timeseries_name'), 'timeseries', type_='unique')
    op.create_unique_constraint('uq_timeseries_campaign_id', 'timeseries', ['campaign_id', 'name'])
    # ### end Alembic commands ###
