"""new migration

Revision ID: 38493c41ebc8
Revises: 61ea1472fd11
Create Date: 2024-08-03 23:05:28.983706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38493c41ebc8'
down_revision = '4037240ac459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['u_groups.id'], name=op.f('fk_teams_user_group_id_u_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
