"""add created by and name column in the members table

Revision ID: 3ecbccb60140
Revises: 4876c82dc52d
Create Date: 2024-09-10 21:39:07.357983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecbccb60140'
down_revision = '4876c82dc52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('name', sa.String(length=80), nullable=False))
    op.create_foreign_key(op.f('fk_members_created_by_users'), 'members', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_members_created_by_users'), 'members', type_='foreignkey')
    op.drop_column('members', 'name')
    op.drop_column('members', 'created_by')
    # ### end Alembic commands ###
