"""add unique contraint for device and device by timeseries

Revision ID: 4037240ac459
Revises: 4b35130d195e
Create Date: 2024-08-03 22:08:31.549106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4037240ac459'
down_revision = '4b35130d195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_devices_unique_identifier'), 'devices', ['unique_identifier'])
    op.create_unique_constraint(op.f('uq_devices_by_timeseries_device_id'), 'devices_by_timeseries', ['device_id', 'timeseries_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_devices_by_timeseries_device_id'), 'devices_by_timeseries', type_='unique')
    op.drop_constraint(op.f('uq_devices_unique_identifier'), 'devices', type_='unique')
    # ### end Alembic commands ###
