"""alter the teams and members tables

Revision ID: 4876c82dc52d
Revises: f74ff568eb5e
Create Date: 2024-09-08 12:06:40.143221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4876c82dc52d'
down_revision = 'f74ff568eb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_members_user_id_users'), 'members', 'users', ['user_id'], ['id'])
    op.drop_column('members', 'first_name')
    op.drop_column('members', 'last_name')
    op.alter_column('teams', 'user_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'user_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('members', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_members_user_id_users'), 'members', type_='foreignkey')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
