"""devices model

Revision ID: 4b35130d195e
Revises: 61ea1472fd11
Create Date: 2024-07-31 16:20:41.574215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b35130d195e'
down_revision = '61ea1472fd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicecategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devicecategory'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('unique_identifier', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'DISABLED', name='devicestatus'), nullable=False),
    sa.Column('energy_rating', sa.String(length=20), nullable=True),
    sa.Column('device_category_id', sa.Integer(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_devices_building_id_buildings')),
    sa.ForeignKeyConstraint(['device_category_id'], ['devicecategory.id'], name=op.f('fk_devices_device_category_id_devicecategory')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_table('devices_by_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_devices_by_timeseries_device_id_devices')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_devices_by_timeseries_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices_by_timeseries'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices_by_timeseries')
    op.drop_table('devices')
    op.drop_table('devicecategory')
    # ### end Alembic commands ###
