"""add auth token model

Revision ID: 61ea1472fd11
Revises: 0.15
Create Date: 2024-07-22 17:43:44.759578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ea1472fd11'
down_revision = '0.15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticationtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_authenticationtoken_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authenticationtoken'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authenticationtoken')
    # ### end Alembic commands ###
