"""add timestamp column

Revision ID: 6a099622c512
Revises: 8ae0fa2d843b
Create Date: 2024-08-15 05:42:31.077656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a099622c512'
down_revision = '8ae0fa2d843b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'timestamp')
    # ### end Alembic commands ###
