"""add device to ts_data

Revision ID: 73b52b222bd5
Revises: e187ef8944ec
Create Date: 2024-10-01 20:50:02.533382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b52b222bd5'
down_revision = 'e187ef8944ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ts_data', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_ts_data_device_id_devices'), 'ts_data', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ts_data_device_id_devices'), 'ts_data', type_='foreignkey')
    op.drop_column('ts_data', 'device_id')
    # ### end Alembic commands ###
