"""add member model class

Revision ID: 75d0c05b5f3b
Revises: 38493c41ebc8
Create Date: 2024-08-07 14:56:20.297485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d0c05b5f3b'
down_revision = '38493c41ebc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('permission_level', sa.String(length=10), nullable=False),
    sa.Column('authorized_locations', sa.String(length=255), nullable=True),
    sa.Column('contact_information', sa.String(length=255), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_members_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
