"""return the user id column in threshold table

Revision ID: 7d81247e0d4b
Revises: 93172634cba1
Create Date: 2024-08-20 09:24:05.219786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d81247e0d4b'
down_revision = '93172634cba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thresholds', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_thresholds_user_id_users'), 'thresholds', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_thresholds_user_id_users'), 'thresholds', type_='foreignkey')
    op.drop_column('thresholds', 'user_id')
    # ### end Alembic commands ###
