"""alter peak usage time column to be true

Revision ID: 892756b791e3
Revises: e71bdd7e0653
Create Date: 2024-10-24 20:49:45.018596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '892756b791e3'
down_revision = 'e71bdd7e0653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'peak_usage_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'peak_usage_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
