"""edit the alerts columns model file

Revision ID: 945ea3fe86fa
Revises: 909e41a1cdd5
Create Date: 2024-08-14 21:46:01.955796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '945ea3fe86fa'
down_revision = '909e41a1cdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('consumption', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('alerts', sa.Column('action_required', sa.String(length=200), nullable=True))
    op.add_column('alerts', sa.Column('location', sa.String(length=100), nullable=False))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolution_description', sa.String(length=200), nullable=True))
    op.add_column('alerts', sa.Column('action_taken', sa.String(length=200), nullable=True))
    op.create_foreign_key(op.f('fk_alerts_resolved_by_user_id_users'), 'alerts', 'users', ['resolved_by_user_id'], ['id'])
    op.drop_column('alerts', 'timestamp')
    op.drop_column('alerts', 'actual_consumption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('actual_consumption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_alerts_resolved_by_user_id_users'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'action_taken')
    op.drop_column('alerts', 'resolution_description')
    op.drop_column('alerts', 'resolved_by_user_id')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'location')
    op.drop_column('alerts', 'action_required')
    op.drop_column('alerts', 'description')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'consumption')
    # ### end Alembic commands ###
