"""add password column

Revision ID: a643750b3d94
Revises: 539e3808a99b
Create Date: 2024-09-12 09:14:18.604253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a643750b3d94'
down_revision = '539e3808a99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'password')
    # ### end Alembic commands ###
