"""add new table for threshold data

Revision ID: b0c23e71cece
Revises: 799e288b6b1e
Create Date: 2024-08-18 15:08:28.229344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c23e71cece'
down_revision = '799e288b6b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_thresholds_device_id_devices')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_thresholds_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thresholds'))
    )
    op.add_column('alerts', sa.Column('threshold_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_alerts_threshold_id_thresholds'), 'alerts', 'thresholds', ['threshold_id'], ['id'])
    op.drop_column('alerts', 'threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_alerts_threshold_id_thresholds'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'threshold_id')
    op.drop_table('thresholds')
    # ### end Alembic commands ###
