"""edit the resolved by column

Revision ID: d21c59a52cbd
Revises: 945ea3fe86fa
Create Date: 2024-08-15 05:09:46.146884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21c59a52cbd'
down_revision = '945ea3fe86fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_by', sa.String(length=80), nullable=True))
    op.drop_constraint('fk_alerts_resolved_by_user_id_users', 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'resolved_by_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_alerts_resolved_by_user_id_users', 'alerts', 'users', ['resolved_by_user_id'], ['id'])
    op.drop_column('alerts', 'resolved_by')
    # ### end Alembic commands ###
