"""edit name of contact column to email

Revision ID: e179e65c2ed7
Revises: 3ecbccb60140
Create Date: 2024-09-11 21:36:44.734464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e179e65c2ed7'
down_revision = '3ecbccb60140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('members', 'contact_information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('contact_information', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('members', 'email')
    # ### end Alembic commands ###
