"""add user id column

Revision ID: e187ef8944ec
Revises: 05785b896490
Create Date: 2024-09-15 21:28:01.921048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e187ef8944ec'
down_revision = '05785b896490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_members_user_id_users'), 'members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_members_user_id_users'), 'members', type_='foreignkey')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
