"""alter peak usage time column

Revision ID: e71bdd7e0653
Revises: 120a191ef164
Create Date: 2024-10-18 14:07:55.230070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71bdd7e0653'
down_revision = '120a191ef164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'peak_usage_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'peak_usage_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
